### PR TITLE
Updated to API 11

### PR DESCRIPTION
**Pull request by RDalcolmo**
Updated to API 11 and off vulnerable packages

### CODE REVIEW

**Comment by Aspher0** [comment]
In NaviMapManager.cs, I would suggest doing this instead.
Also, the PR is massive and may conflict with any possible changes the dev might have added.

```c#
public void UpdateMap()
{
    if (_maps != null)
    {
        try
        {
            var map = _maps.GetRow(GetMapId());

            if (map.SizeFactor != 0)
            {
                ZoneScale = (float)map.SizeFactor / 100;
            }
            else
            {
                ZoneScale = 1;
            }
            OffsetX = map.OffsetX;
            OffsetY = map.OffsetY;
        }
        catch
        {
            return;
        }
    }
}
```

**Comment by RDalcolmo** [comment]
I made the change, I agree catching it as an exception may be more appropriate

**Comment by jaycewhite** [comment]
Hey! This all looks good to me, and i've tested it in game and it all seems to work great! I'm just going to do a bit more testing but after that I'll merge this in and get it released. Thanks for your work!

**Comment by RDalcolmo** [comment]
You're welcome! I love this plugin

**Pull request merged**
